### ISSUE TITLE
Where is the Audio part?

### ISSUE THREAD

**Issue by luxtiasco** [DAMO-NLP-SG/Video-LLaMA#18]
It is titled: An Instruction-tuned Audio-Visual Language Model for Video Understanding 
But I am having no idea on audio model.

**Comment by lixin4ever** [comment]
Thank you for your attention. The current stuff (figure, checkpoints, demos, example outputs, etc.) in the repo is for the previous version of Video-LLaMA, which is solely based on video frames. We have not yet updated the repo to the latest version that supports audio input. You can refer to our [technical report](https://arxiv.org/pdf/2306.02858.pdf) for the details of audio modeling.

**Comment by tensorboy** [comment]
Is the audio part fully opened?

**Comment by lixin4ever** [comment]
The checkpoints for the latest version of our Video-LLaMA (audio input supported) have been uploaded but the online interactive demo for this version is still not ready due to the limit of GPU memory (even with Vicuna-7B as decoder). Nevertheless, you can try to run the demo locally, more details can be found [here](https://github.com/DAMO-NLP-SG/Video-LLaMA#usage).
